// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_gametes_batch_cpp
List make_gametes_batch_cpp(IntegerMatrix parent_allele, IntegerMatrix parent_lo_code, IntegerVector gamete_parent_idx, IntegerVector gamete_o, IntegerVector gamete_origin, IntegerVector chr_start, IntegerVector chr_end, NumericVector chr_pos_cM, NumericVector chr_len_cM, int base_seed, bool store_crossovers);
RcppExport SEXP _tidybreed_make_gametes_batch_cpp(SEXP parent_alleleSEXP, SEXP parent_lo_codeSEXP, SEXP gamete_parent_idxSEXP, SEXP gamete_oSEXP, SEXP gamete_originSEXP, SEXP chr_startSEXP, SEXP chr_endSEXP, SEXP chr_pos_cMSEXP, SEXP chr_len_cMSEXP, SEXP base_seedSEXP, SEXP store_crossoversSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type parent_allele(parent_alleleSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type parent_lo_code(parent_lo_codeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gamete_parent_idx(gamete_parent_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gamete_o(gamete_oSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gamete_origin(gamete_originSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chr_start(chr_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chr_end(chr_endSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type chr_pos_cM(chr_pos_cMSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type chr_len_cM(chr_len_cMSEXP);
    Rcpp::traits::input_parameter< int >::type base_seed(base_seedSEXP);
    Rcpp::traits::input_parameter< bool >::type store_crossovers(store_crossoversSEXP);
    rcpp_result_gen = Rcpp::wrap(make_gametes_batch_cpp(parent_allele, parent_lo_code, gamete_parent_idx, gamete_o, gamete_origin, chr_start, chr_end, chr_pos_cM, chr_len_cM, base_seed, store_crossovers));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidybreed_make_gametes_batch_cpp", (DL_FUNC) &_tidybreed_make_gametes_batch_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidybreed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
