#' Define founder haplotypes for a tidybreed population
#'
#' @description
#' Generates a pool of founder haplotypes and stores them in the
#' `founder_haplotypes` table. This table is required by [add_founders()] to
#' assign phased alleles to new individuals.
#'
#' Call this function after [define_genome()] and before [add_founders()].
#' You may call it **multiple times** with different `line_name` values to
#' create line-specific haplotype pools (e.g., different LD structures per
#' line). [add_founders()] will then sample only from the pool matching its
#' own `line_name` argument.
#'
#' Also writes a `founder_allele_freq` column to `genome_meta` recording the
#' per-locus allele frequency of the most recently generated pool (the empirical
#' column mean for LD methods and for `exact_freq = TRUE`; the sampled target
#' otherwise). This column is **informational only** — no other tidybreed
#' function reads it, and because each call rewrites it for every locus, in a
#' multi-line setup it describes only the pool written last. For multi-line
#' setups needing accurate per-line Falconer centering, use
#' `base = "current_pop"` in [define_additive_effects()] instead: with
#' `base = "founder_haplotypes"` the base frequency is recomputed by pooling
#' **all** lines' haplotypes together.
#'
#' @section Methods:
#' \describe{
#'   \item{`"uniform"` (default)}{Per-locus allele frequency sampled from
#'     Uniform(`min_allele_freq`, `max_allele_freq`). No LD structure.}
#'   \item{`"fixed"`}{Every locus gets the same `allele_freq` (default 0.5),
#'     **exactly**. Rather than drawing each allele as a Bernoulli(`allele_freq`)
#'     trial — which leaves the realized pool frequency fluctuating binomially
#'     around the target — exactly `round(allele_freq × n_haplotypes)` of the
#'     haplotypes carry the 1-allele at each locus, on an independently drawn
#'     random subset per locus (so no LD is induced). No LD structure.}
#'   \item{`"beta"`}{Per-locus allele frequency sampled from
#'     Beta(`beta_shape1`, `beta_shape2`). Default `shape1 = shape2 = 0.5`
#'     (Jeffreys prior) gives a U-shaped MAF distribution with many rare and
#'     common alleles — biologically realistic. No LD structure.}
#'   \item{`"balding_nichols"`}{Balding-Nichols model: per-locus frequency
#'     from Beta(α, β) where α = `mean_allele_freq` × (1 − `fst`) / `fst` and
#'     β = (1 − `mean_allele_freq`) × (1 − `fst`) / `fst`. Models allele
#'     frequency drift around a mean. No LD structure.}
#'   \item{`"mosaic"`}{Quick LD via haplotype block copying. Generates
#'     `n_templates` template haplotypes, then builds each new haplotype as a
#'     mosaic: copies from a template and re-draws a template with probability
#'     `1 - exp(-template_switch_rate × d_cM)` at each locus. Creates realistic
#'     LD blocks without external software. Uses the genetic map (`genome_map`)
#'     resolved for this pool's `line_name` for adjacent-locus distances.
#'     Performance is O(n_haplotypes × n_loci); use `"gaussian_copula"` for very
#'     large simulations.
#'
#'   Two properties of this model are easy to miss. First, the re-draw is
#'   uniform over **all** templates including the current one, so the rate of
#'   *observable* template changes is
#'   `template_switch_rate × (n_templates − 1) / n_templates`. This is
#'   deliberate — it is the standard Li-Stephens copying kernel, and it is what
#'   makes realized LD invariant to marker density. Second, templates are the
#'   only source of allelic variation, so a locus where all `n_templates`
#'   templates agree is monomorphic **regardless of `n_haplotypes`**; roughly
#'   `2 / (n_templates + 1)` of loci are monomorphic, and the MAF spectrum is
#'   quantized to multiples of `1 / n_templates`. Raise `n_templates` if you
#'   need rare variants or a dense MAF spectrum.}
#'   \item{`"gaussian_copula"`}{Fast LD via AR(1) latent normal. A latent
#'     Gaussian AR(1) process runs along each chromosome; adjacent-locus
#'     correlation decays as ρ = exp(−`ld_decay_rate` × d_cM). Haplotypes are
#'     generated by thresholding latent values at each locus's target allele
#'     frequency. Fully vectorised over haplotypes, and unlike `"mosaic"` it
#'     produces an unquantized MAF spectrum. Uses the genetic map (`genome_map`)
#'     resolved for this pool's `line_name`.}
#' }
#'
#' @param pop A `tidybreed_pop` object returned by [define_genome()].
#' @param n_haplotypes Positive integer. Number of founder haplotypes to
#'   generate.
#' @param method Character scalar. One of `"uniform"` (default), `"fixed"`,
#'   `"beta"`, `"balding_nichols"`, `"mosaic"`, or `"gaussian_copula"`.
#'   Passing an argument that belongs to a different method raises an error.
#' @param allele_freq *(method = "fixed" only)* Numeric scalar in \[0, 1\].
#'   Allele frequency realized *exactly* at every locus. Default `0.5`.
#'   Frequencies live on a `1 / n_haplotypes` grid; if
#'   `allele_freq × n_haplotypes` is not a whole number it is rounded, with a
#'   warning naming the frequency actually used.
#' @param min_allele_freq *(method = "uniform" only)* Lower bound. Default
#'   `0.01`.
#' @param max_allele_freq *(method = "uniform" only)* Upper bound. Default
#'   `0.99`.
#' @param beta_shape1 *(method = "beta" only)* First Beta shape parameter (α).
#'   Must be finite and > 0. Default `0.5`.
#' @param beta_shape2 *(method = "beta" only)* Second Beta shape parameter (β).
#'   Must be finite and > 0. Default `0.5`.
#' @param fst *(method = "balding_nichols" only)* Wright's F_ST. Scalar in
#'   (0, 1). Controls spread of frequencies around `mean_allele_freq`; larger
#'   values produce more extreme frequencies. Default `0.1`.
#' @param mean_allele_freq *(method = "balding_nichols" only)* Ancestral mean
#'   allele frequency. Scalar in (0, 1). Default `0.5`.
#' @param n_templates *(method = "mosaic" only)* Number of template haplotypes.
#'   Must be a whole number in `[2, n_haplotypes]`. Also controls the MAF
#'   spectrum — see the `"mosaic"` entry above. Default
#'   `max(20, ceiling(sqrt(n_haplotypes)))`, clamped to `n_haplotypes`. The
#'   floor of 20 keeps the expected monomorphic fraction near 10%; lower it only
#'   if you deliberately want long, coarse LD blocks.
#' @param template_switch_rate *(method = "mosaic" only)* Template re-draw rate
#'   per cM (genetic distance). Higher values create shorter LD blocks. `0`
#'   means never switch (complete LD within a chromosome). Note that observable
#'   template *changes* occur at
#'   `template_switch_rate × (n_templates − 1) / n_templates` — see the
#'   `"mosaic"` entry above. Default `1.0`. (At the default `cM_per_Mb = 1`,
#'   per-cM equals per-Mb.)
#' @param ld_decay_rate *(method = "gaussian_copula" only)* LD decay rate λ in
#'   ρ = exp(−λ × d_cM). Higher values → faster LD decay. `0` means no decay
#'   (complete LD within a chromosome). Default `1.0` gives ρ ≈ 0.37 at 1 cM.
#' @param exact_freq *(methods "fixed", "uniform", "beta", "balding_nichols")*
#'   Logical. When `TRUE`, each locus receives exactly
#'   `round(p × n_haplotypes)` copies of the 1-allele on an independently drawn
#'   random subset of haplotypes, so the **realized** pool frequency equals the
#'   per-locus target `p` with no binomial fluctuation (no LD is induced —
#'   each locus draws its own subset). When `FALSE`, alleles are drawn as
#'   independent `Bernoulli(p)` trials, so realized frequencies scatter around
#'   `p` with sd `sqrt(p(1-p)/n_haplotypes)`.
#'
#'   Defaults to `TRUE` for `method = "fixed"` (a "fixed" frequency that drifts
#'   is not fixed) and `FALSE` for the distribution-based methods, where drawing
#'   a frequency and then sampling alleles binomially is the correct generative
#'   model. Set `TRUE` on those methods when you want `founder_allele_freq` to
#'   be the exact base frequency for Falconer centering. Frequencies are snapped
#'   to the `1 / n_haplotypes` grid; for `method = "fixed"` a warning names the
#'   frequency actually used when the requested one is off-grid (for the
#'   distribution methods a continuous draw is essentially never on the grid, so
#'   rounding is silent).
#' @param line_name Optional character scalar. A label for this haplotype pool
#'   (e.g. `"LineA"`). Must start with a letter and contain only letters,
#'   numbers, or underscores. When supplied, `founder_haplotypes` rows are
#'   tagged with this label (`haplotype_id` is sequential within the pool).
#'   [add_founders()] with the same `line_name` will sample exclusively from
#'   these rows. When `NULL` (default), rows are stored with `line_name = NA`
#'   and [add_founders()] falls back to them when no named pool exists for the
#'   requested line.
#'
#' @return The `tidybreed_pop` object (invisibly), with `founder_haplotypes`
#'   registered in `pop$tables` and `founder_allele_freq` added to `genome_meta`.
#'
#' @seealso [define_genome()], [add_founders()]
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Each method demo below starts from a fresh pop — define_founder_haplotypes()
#' # errors if called again with line_name = NULL once a NULL-line pool already
#' # exists, so these are alternative choices, not a sequential recipe.
#' new_pop <- function() {
#'   open_pop(pop_name = "A", db_name = ":memory:") |>
#'     define_genome(n_loci = 1000, n_chr = 10, chr_len_Mb = 100)
#' }
#'
#' # Uniform allele frequencies (default)
#' pop <- new_pop() |> define_founder_haplotypes(n_haplotypes = 200)
#'
#' # Fixed allele frequency of 0.5
#' pop <- new_pop() |> define_founder_haplotypes(n_haplotypes = 200, method = "fixed")
#'
#' # Beta(0.5, 0.5) — biologically realistic MAF distribution
#' pop <- new_pop() |> define_founder_haplotypes(n_haplotypes = 200, method = "beta")
#'
#' # Balding-Nichols with FST = 0.05
#' pop <- new_pop() |> define_founder_haplotypes(n_haplotypes = 200,
#'                                  method = "balding_nichols", fst = 0.05)
#'
#' # Beta frequencies, realized exactly (no binomial scatter around the draw)
#' pop <- new_pop() |> define_founder_haplotypes(n_haplotypes = 200,
#'                                  method = "beta", exact_freq = TRUE)
#'
#' # Quick LD via mosaic block copying
#' pop <- new_pop() |> define_founder_haplotypes(n_haplotypes = 200, method = "mosaic")
#'
#' # Fast LD via Gaussian copula AR(1)
#' pop <- new_pop() |> define_founder_haplotypes(n_haplotypes = 200,
#'                                  method = "gaussian_copula", ld_decay_rate = 0.5)
#'
#' # Two lines with different LD structures (same pop, distinct line_name)
#' pop <- new_pop()
#' pop <- pop |> define_founder_haplotypes(n_haplotypes = 200, line_name = "A",
#'                                  method = "mosaic")
#' pop <- pop |> define_founder_haplotypes(n_haplotypes = 200, line_name = "B",
#'                                  method = "gaussian_copula", ld_decay_rate = 0.5)
#' }
define_founder_haplotypes <- function(
    pop,
    n_haplotypes,
    method          = "uniform",
    # method = "fixed"
    allele_freq     = NULL,
    # method = "uniform"
    min_allele_freq = NULL,
    max_allele_freq = NULL,
    # method = "beta"
    beta_shape1     = NULL,
    beta_shape2     = NULL,
    # method = "balding_nichols"
    fst             = NULL,
    mean_allele_freq = NULL,
    # method = "mosaic"
    n_templates     = NULL,
    template_switch_rate = NULL,
    # method = "gaussian_copula"
    ld_decay_rate   = NULL,
    # methods "fixed", "uniform", "beta", "balding_nichols"
    exact_freq      = NULL,
    # line label
    line_name       = NULL
) {

  stopifnot(inherits(pop, "tidybreed_pop"))
  validate_tidybreed_pop(pop)

  # Validate BEFORE as.integer(): checking `> 0` first would let 0 < n < 1
  # coerce to 0L and fail much later inside .write_founder_haplotypes().
  n_haplotypes <- .check_scalar(n_haplotypes, "n_haplotypes", min = 1,
                                whole = TRUE)

  method <- match.arg(method, c("fixed", "uniform", "beta",
                                 "balding_nichols", "mosaic", "gaussian_copula"))

  if (!is.null(line_name)) {
    stopifnot(is.character(line_name), length(line_name) == 1L, nchar(line_name) > 0)
    if (!grepl("^[a-zA-Z][a-zA-Z0-9_]*$", line_name)) {
      stop(
        "line_name must start with a letter and contain only letters, numbers, or underscores.",
        call. = FALSE
      )
    }
  }

  # --- Wrong-method argument validation ---
  # Single source of truth: argument -> the method(s) that accept it. Supplied
  # values are read back with mget(), so there is no second hand-maintained list
  # that could drift out of sync with this one. `exact_freq` is shared by all
  # four frequency-based methods, which is why the mapping runs arg -> methods
  # rather than method -> args.
  ARG_METHODS <- list(
    allele_freq          = "fixed",
    min_allele_freq      = "uniform",
    max_allele_freq      = "uniform",
    beta_shape1          = "beta",
    beta_shape2          = "beta",
    fst                  = "balding_nichols",
    mean_allele_freq     = "balding_nichols",
    n_templates          = "mosaic",
    template_switch_rate = "mosaic",
    ld_decay_rate        = "gaussian_copula",
    exact_freq           = c("fixed", "uniform", "beta", "balding_nichols")
  )
  supplied <- mget(names(ARG_METHODS))
  for (arg in names(ARG_METHODS)) {
    owners <- ARG_METHODS[[arg]]
    if (!is.null(supplied[[arg]]) && !method %in% owners) {
      stop(
        "Argument `", arg, "` belongs to method = ",
        paste0("\"", owners, "\"", collapse = " or "), ", ",
        "but method = \"", method, "\" was requested. ",
        "Remove `", arg, "` or change method.",
        call. = FALSE
      )
    }
  }

  # --- Guards ---
  # Ask the database, not the in-memory pop$tables registry, so this matches the
  # sibling dbExistsTable() check below and stays correct for a restored session.
  if (!DBI::dbExistsTable(pop$db_conn, "genome_meta")) {
    stop(
      "genome_meta table does not exist. ",
      "Call define_genome() before define_founder_haplotypes().",
      call. = FALSE
    )
  }
  if (DBI::dbExistsTable(pop$db_conn, "founder_haplotypes")) {
    fh_cols <- DBI::dbListFields(pop$db_conn, "founder_haplotypes")
    if (!"line_name" %in% fh_cols) {
      stop(
        "founder_haplotypes table exists but has no line_name column (old format). ",
        "Recreate the population to use the multi-line API.",
        call. = FALSE
      )
    }
    if (is.null(line_name)) {
      n_null <- DBI::dbGetQuery(
        pop$db_conn,
        "SELECT COUNT(*) AS n FROM founder_haplotypes WHERE line_name IS NULL"
      )$n
      if (n_null > 0L) {
        stop(
          "founder_haplotypes already contains haplotypes with line_name = NULL. ",
          "Supply a line_name or drop the table before calling again.",
          call. = FALSE
        )
      }
    } else {
      # Parameterized rather than interpolated: the regex above already rejects
      # every quoting character, but this removes the dependency on a validation
      # 70 lines away.
      n_line <- DBI::dbGetQuery(
        pop$db_conn,
        "SELECT COUNT(*) AS n FROM founder_haplotypes WHERE line_name = ?",
        params = list(line_name)
      )$n
      if (n_line > 0L) {
        stop(
          "founder_haplotypes already contains haplotypes for line '", line_name, "'. ",
          "Drop the table or use a different line_name.",
          call. = FALSE
        )
      }
    }
  }

  n_loci <- DBI::dbGetQuery(pop$db_conn, "SELECT COUNT(*) AS n FROM genome_meta")$n
  n_loci <- as.integer(n_loci)
  if (n_loci == 0L) {
    stop("genome_meta is empty. Cannot generate founder haplotypes.", call. = FALSE)
  }

  # LD methods (mosaic, gaussian_copula) traverse loci by genetic distance and
  # fetch the resolved default map lazily (see their branches). Simple methods
  # need no map; write-back is self-contained in .write_founder_haplotypes().

  # --- Per-method argument resolution and validation ---
  # Runs BEFORE the progress message so a bad parameter never prints
  # "Generating ..." and then errors.
  if (method %in% c("fixed", "uniform", "beta", "balding_nichols")) {
    # fixed realises its target exactly by default; the distribution-based
    # methods sample binomially by default, which is their correct model.
    exact_freq <- if (is.null(exact_freq)) identical(method, "fixed") else
      .check_flag(exact_freq, "exact_freq")
  }

  if (method == "fixed") {
    if (is.null(allele_freq)) allele_freq <- 0.5
    allele_freq <- .check_scalar(allele_freq, "allele_freq", min = 0, max = 1)

  } else if (method == "uniform") {
    if (is.null(min_allele_freq)) min_allele_freq <- 0.01
    if (is.null(max_allele_freq)) max_allele_freq <- 0.99
    min_allele_freq <- .check_scalar(min_allele_freq, "min_allele_freq",
                                     min = 0, max = 1)
    max_allele_freq <- .check_scalar(max_allele_freq, "max_allele_freq",
                                     min = 0, max = 1)
    if (min_allele_freq >= max_allele_freq) {
      stop("`min_allele_freq` (", min_allele_freq, ") must be less than ",
           "`max_allele_freq` (", max_allele_freq, ").", call. = FALSE)
    }

  } else if (method == "beta") {
    if (is.null(beta_shape1)) beta_shape1 <- 0.5
    if (is.null(beta_shape2)) beta_shape2 <- 0.5
    beta_shape1 <- .check_scalar(beta_shape1, "beta_shape1", min = 0,
                                 exclusive = TRUE)
    beta_shape2 <- .check_scalar(beta_shape2, "beta_shape2", min = 0,
                                 exclusive = TRUE)

  } else if (method == "balding_nichols") {
    if (is.null(fst))              fst              <- 0.1
    if (is.null(mean_allele_freq)) mean_allele_freq <- 0.5
    fst <- .check_scalar(fst, "fst", min = 0, max = 1, exclusive = TRUE)
    mean_allele_freq <- .check_scalar(mean_allele_freq, "mean_allele_freq",
                                      min = 0, max = 1, exclusive = TRUE)

  } else if (method == "mosaic") {
    if (is.null(n_templates)) {
      # Floor of 20 rather than 2: templates are the only source of allelic
      # variation, so ~2/(K+1) of loci come out monomorphic regardless of
      # n_haplotypes. The old sqrt-only default gave K = 10 at 100 haplotypes
      # (~17% dead loci); a floor of 20 halves that. Clamped to n_haplotypes so
      # a small pool cannot trip the n_templates <= n_haplotypes check below.
      n_templates <- max(2L, min(as.integer(n_haplotypes),
                                 max(20L, as.integer(ceiling(sqrt(n_haplotypes))))))
    }
    if (is.null(template_switch_rate)) template_switch_rate <- 1.0
    # Validate BEFORE as.integer(): coercing first would make the type check
    # tautological and silently accept a string or truncate a fraction.
    n_templates <- .check_scalar(n_templates, "n_templates", min = 2,
                                 whole = TRUE)
    if (n_templates > n_haplotypes) {
      stop("`n_templates` (", n_templates, ") must not exceed `n_haplotypes` (",
           n_haplotypes, "); extra templates add no variation.", call. = FALSE)
    }
    template_switch_rate <- .check_scalar(template_switch_rate,
                                          "template_switch_rate", min = 0)

  } else if (method == "gaussian_copula") {
    if (is.null(ld_decay_rate)) ld_decay_rate <- 1.0
    # 0 is allowed, matching template_switch_rate = 0: both are the same
    # well-defined maximum-LD limit (complete LD within a chromosome).
    ld_decay_rate <- .check_scalar(ld_decay_rate, "ld_decay_rate", min = 0)
  }

  message("Generating ", n_haplotypes,
          " founder haplotypes (method = \"", method, "\")...")

  # --- Dispatch ---
  if (method %in% c("fixed", "uniform", "beta", "balding_nichols")) {
    allele_freqs <- switch(
      method,
      fixed           = .gen_allele_freqs_fixed(n_loci, allele_freq),
      uniform         = .gen_allele_freqs_uniform(n_loci, min_allele_freq,
                                                  max_allele_freq),
      beta            = .gen_allele_freqs_beta(n_loci, beta_shape1, beta_shape2),
      balding_nichols = .gen_allele_freqs_balding_nichols(n_loci, fst,
                                                          mean_allele_freq)
    )
    if (exact_freq) {
      # Exact allocation rather than Bernoulli sampling: the realised pool
      # frequency equals the target, snapped to the 1/n_haplotypes grid.
      haplotype_matrix <- .gen_haplotypes_exact_freqs(n_haplotypes, allele_freqs)
      realised <- round(allele_freqs * n_haplotypes) / n_haplotypes
      # Only warn for "fixed", where the user named one exact target that cannot
      # be honoured. For the distribution methods a continuous draw is virtually
      # never on the 1/n_haplotypes grid, so rounding is inherent rather than
      # surprising -- warning every time would be pure noise.
      if (identical(method, "fixed") &&
            !isTRUE(all.equal(realised[1], allele_freq))) {
        warning(
          "allele_freq = ", allele_freq, " is not exactly representable with ",
          n_haplotypes, " haplotypes. Using ", round(allele_freq * n_haplotypes),
          "/", n_haplotypes, " = ", format(realised[1]), " at every locus.",
          call. = FALSE
        )
      }
      # Store what the pool actually carries, not the pre-rounding target.
      allele_freqs <- realised
    } else {
      haplotype_matrix <- .gen_haplotypes_from_freqs(n_haplotypes, allele_freqs)
    }

  } else {
    # LD methods traverse loci by genetic distance. Resolve the map for THIS
    # pool's line, so founder LD is built on the same map that will later drive
    # recombination for that line (add_offspring() resolves per-parent line).
    # sex = NULL is correct: a founder pool is not sex-specific.
    locus_map <- resolve_genome_map(pop$db_conn, line_name = line_name)
    haplotype_matrix <- if (method == "mosaic") {
      .gen_haplotypes_mosaic(n_haplotypes, n_loci, locus_map, n_templates,
                             template_switch_rate)
    } else {
      .gen_haplotypes_gaussian_copula(n_haplotypes, n_loci, locus_map,
                                      ld_decay_rate)
    }
    # LD methods have no target frequency -- frequencies are emergent, so the
    # realised column mean is the only meaningful value.
    allele_freqs <- colMeans(haplotype_matrix)

    n_mono <- sum(allele_freqs == 0 | allele_freqs == 1)
    if (n_mono > 0.1 * n_loci) {
      warning(
        n_mono, " of ", n_loci, " loci (",
        round(100 * n_mono / n_loci, 1), "%) are monomorphic in this pool",
        if (method == "mosaic")
          paste0(". With n_templates = ", n_templates,
                 ", roughly 2/(n_templates + 1) of loci are expected to be ",
                 "monomorphic regardless of n_haplotypes; raise n_templates ",
                 "for a denser MAF spectrum") else "",
        ". QTL placed on monomorphic loci contribute no genetic variance.",
        call. = FALSE
      )
    }
  }

  pop <- .write_founder_haplotypes(pop, haplotype_matrix, allele_freqs, line_name)

  line_label <- if (!is.null(line_name)) paste0(" for line '", line_name, "'") else ""
  message("  Created founder_haplotypes", line_label, " (",
          n_haplotypes, " haplotypes x ", n_loci, " loci)")

  invisible(pop)
}
