#' Define founder haplotypes for a tidybreed population
#'
#' @description
#' Generates a pool of founder haplotypes and stores them in the
#' `founder_haplotypes` table. This table is required by [add_founders()] to
#' assign phased alleles to new individuals.
#'
#' Call this function after [initialize_genome()] and before [add_founders()].
#' You may call it **multiple times** with different `line_name` values to
#' create line-specific haplotype pools (e.g., different LD structures per
#' line). [add_founders()] will then sample only from the pool matching its
#' own `line_name` argument.
#'
#' Also writes a `founder_allele_freq` column to `genome_meta` recording the
#' per-locus allele frequency of the most recently generated pool (the empirical
#' column mean for LD methods). For multi-line setups needing accurate
#' per-line Falconer centering, use `base = "current_pop"` in
#' [define_additive_effects()] instead.
#'
#' @section Methods:
#' \describe{
#'   \item{`"uniform"` (default)}{Per-locus allele frequency sampled from
#'     Uniform(`min_allele_freq`, `max_allele_freq`). No LD structure.}
#'   \item{`"fixed"`}{Every locus gets the same `allele_freq` (default 0.5).
#'     No LD structure. Useful for quick sanity checks.}
#'   \item{`"beta"`}{Per-locus allele frequency sampled from
#'     Beta(`beta_shape1`, `beta_shape2`). Default `shape1 = shape2 = 0.5`
#'     (Jeffreys prior) gives a U-shaped MAF distribution with many rare and
#'     common alleles — biologically realistic. No LD structure.}
#'   \item{`"balding_nichols"`}{Balding-Nichols model: per-locus frequency
#'     from Beta(α, β) where α = `mean_freq` × (1 − `fst`) / `fst` and
#'     β = (1 − `mean_freq`) × (1 − `fst`) / `fst`. Models allele frequency
#'     drift around a mean. No LD structure.}
#'   \item{`"mosaic"`}{Quick LD via haplotype block copying. Generates
#'     `n_templates` template haplotypes, then builds each new haplotype as a
#'     mosaic: copies from a template and switches templates with probability
#'     `1 - exp(-switch_rate × d_Mb)` at each locus. Creates realistic LD
#'     blocks without external software. Requires `chr` and `pos_Mb` in
#'     `genome_meta`. Performance is O(n_haplotypes × n_loci); use
#'     `"gaussian_copula"` for very large simulations.}
#'   \item{`"gaussian_copula"`}{Fast LD via AR(1) latent normal. A latent
#'     Gaussian AR(1) process runs along each chromosome; adjacent-locus
#'     correlation decays as ρ = exp(−`decay_rate` × d_Mb). Haplotypes are
#'     generated by thresholding latent values at each locus's target allele
#'     frequency. Fully vectorised over haplotypes. Requires `chr` and `pos_Mb`
#'     in `genome_meta`.}
#' }
#'
#' @param pop A `tidybreed_pop` object returned by [initialize_genome()].
#' @param n_haplotypes Positive integer. Number of founder haplotypes to
#'   generate.
#' @param method Character scalar. One of `"uniform"` (default), `"fixed"`,
#'   `"beta"`, `"balding_nichols"`, `"mosaic"`, or `"gaussian_copula"`.
#'   Passing an argument that belongs to a different method raises an error.
#' @param allele_freq *(method = "fixed" only)* Numeric scalar in \[0, 1\].
#'   Allele frequency applied to every locus. Default `0.5`.
#' @param min_allele_freq *(method = "uniform" only)* Lower bound. Default
#'   `0.01`.
#' @param max_allele_freq *(method = "uniform" only)* Upper bound. Default
#'   `0.99`.
#' @param beta_shape1 *(method = "beta" only)* First Beta shape parameter (α).
#'   Must be > 0. Default `0.5`.
#' @param beta_shape2 *(method = "beta" only)* Second Beta shape parameter (β).
#'   Must be > 0. Default `0.5`.
#' @param fst *(method = "balding_nichols" only)* Wright's F_ST. Scalar in
#'   (0, 1). Controls spread of frequencies around `mean_freq`; larger values
#'   produce more extreme frequencies. Default `0.1`.
#' @param mean_freq *(method = "balding_nichols" only)* Ancestral mean allele
#'   frequency. Scalar in (0, 1). Default `0.5`.
#' @param n_templates *(method = "mosaic" only)* Number of template haplotypes.
#'   Must be >= 2. Default `ceiling(sqrt(n_haplotypes))`.
#' @param switch_rate *(method = "mosaic" only)* Expected template switches per
#'   Mb. Higher values create shorter LD blocks. Default `1.0`.
#' @param decay_rate *(method = "gaussian_copula" only)* LD decay rate λ in
#'   ρ = exp(−λ × d_Mb). Higher values → faster LD decay. Default `1.0`
#'   gives ρ ≈ 0.37 at 1 Mb.
#' @param line_name Optional character scalar. A label for this haplotype pool
#'   (e.g. `"LineA"`). Must start with a letter and contain only letters,
#'   numbers, or underscores. When supplied, `founder_haplotypes` rows are
#'   tagged with this label (`haplotype_id` is sequential within the pool).
#'   [add_founders()] with the same `line_name` will sample exclusively from
#'   these rows. When `NULL` (default), rows are stored with `line_name = NA`
#'   and [add_founders()] falls back to them when no named pool exists for the
#'   requested line.
#'
#' @return The `tidybreed_pop` object (invisibly), with `founder_haplotypes`
#'   registered in `pop$tables` and `founder_allele_freq` added to `genome_meta`.
#'
#' @seealso [initialize_genome()], [add_founders()]
#'
#' @export
#'
#' @examples
#' \dontrun{
#' pop <- initialize_genome(
#'   pop_name = "A", n_loci = 1000, n_chr = 10, chr_len_Mb = 100
#' )
#'
#' # Uniform allele frequencies (default)
#' pop |> define_founder_haplotypes(n_haplotypes = 200)
#'
#' # Fixed allele frequency of 0.5
#' pop |> define_founder_haplotypes(n_haplotypes = 200, method = "fixed")
#'
#' # Beta(0.5, 0.5) — biologically realistic MAF distribution
#' pop |> define_founder_haplotypes(n_haplotypes = 200, method = "beta")
#'
#' # Balding-Nichols with FST = 0.05
#' pop |> define_founder_haplotypes(n_haplotypes = 200,
#'                                  method = "balding_nichols", fst = 0.05)
#'
#' # Quick LD via mosaic block copying
#' pop |> define_founder_haplotypes(n_haplotypes = 200, method = "mosaic")
#'
#' # Fast LD via Gaussian copula AR(1)
#' pop |> define_founder_haplotypes(n_haplotypes = 200,
#'                                  method = "gaussian_copula", decay_rate = 0.5)
#'
#' # Two lines with different LD structures
#' pop |> define_founder_haplotypes(n_haplotypes = 200, line_name = "A",
#'                                  method = "mosaic")
#' pop |> define_founder_haplotypes(n_haplotypes = 200, line_name = "B",
#'                                  method = "gaussian_copula", decay_rate = 0.5)
#' }
define_founder_haplotypes <- function(
    pop,
    n_haplotypes,
    method          = "uniform",
    # method = "fixed"
    allele_freq     = NULL,
    # method = "uniform"
    min_allele_freq = NULL,
    max_allele_freq = NULL,
    # method = "beta"
    beta_shape1     = NULL,
    beta_shape2     = NULL,
    # method = "balding_nichols"
    fst             = NULL,
    mean_freq       = NULL,
    # method = "mosaic"
    n_templates     = NULL,
    switch_rate     = NULL,
    # method = "gaussian_copula"
    decay_rate      = NULL,
    # line label
    line_name       = NULL
) {

  stopifnot(inherits(pop, "tidybreed_pop"))
  validate_tidybreed_pop(pop)

  stopifnot(is.numeric(n_haplotypes), length(n_haplotypes) == 1L, n_haplotypes > 0)
  n_haplotypes <- as.integer(n_haplotypes)

  method <- match.arg(method, c("fixed", "uniform", "beta",
                                 "balding_nichols", "mosaic", "gaussian_copula"))

  if (!is.null(line_name)) {
    stopifnot(is.character(line_name), length(line_name) == 1L, nchar(line_name) > 0)
    if (!grepl("^[a-zA-Z][a-zA-Z0-9_]*$", line_name)) {
      stop(
        "line_name must start with a letter and contain only letters, numbers, or underscores.",
        call. = FALSE
      )
    }
  }

  # --- Wrong-method argument validation ---
  # Any non-NULL arg that belongs to a different method is an error.
  METHOD_ARGS <- list(
    fixed           = "allele_freq",
    uniform         = c("min_allele_freq", "max_allele_freq"),
    beta            = c("beta_shape1", "beta_shape2"),
    balding_nichols = c("fst", "mean_freq"),
    mosaic          = c("n_templates", "switch_rate"),
    gaussian_copula = "decay_rate"
  )
  all_method_args <- list(
    allele_freq     = allele_freq,
    min_allele_freq = min_allele_freq,
    max_allele_freq = max_allele_freq,
    beta_shape1     = beta_shape1,
    beta_shape2     = beta_shape2,
    fst             = fst,
    mean_freq       = mean_freq,
    n_templates     = n_templates,
    switch_rate     = switch_rate,
    decay_rate      = decay_rate
  )
  for (other_method in setdiff(names(METHOD_ARGS), method)) {
    for (arg in METHOD_ARGS[[other_method]]) {
      if (!is.null(all_method_args[[arg]])) {
        stop(
          "Argument `", arg, "` belongs to method = \"", other_method, "\", ",
          "but method = \"", method, "\" was requested. ",
          "Remove `", arg, "` or change method.",
          call. = FALSE
        )
      }
    }
  }

  # --- Guards ---
  if (!"genome_meta" %in% pop$tables) {
    stop(
      "genome_meta table does not exist. ",
      "Call initialize_genome() before define_founder_haplotypes().",
      call. = FALSE
    )
  }
  if (DBI::dbExistsTable(pop$db_conn, "founder_haplotypes")) {
    fh_cols <- DBI::dbListFields(pop$db_conn, "founder_haplotypes")
    if (!"line_name" %in% fh_cols) {
      stop(
        "founder_haplotypes table exists but has no line_name column (old format). ",
        "Recreate the population to use the multi-line API.",
        call. = FALSE
      )
    }
    if (is.null(line_name)) {
      n_null <- DBI::dbGetQuery(
        pop$db_conn,
        "SELECT COUNT(*) AS n FROM founder_haplotypes WHERE line_name IS NULL"
      )$n
      if (n_null > 0L) {
        stop(
          "founder_haplotypes already contains haplotypes with line_name = NULL. ",
          "Supply a line_name or drop the table before calling again.",
          call. = FALSE
        )
      }
    } else {
      n_line <- DBI::dbGetQuery(
        pop$db_conn,
        sprintf(
          "SELECT COUNT(*) AS n FROM founder_haplotypes WHERE line_name = '%s'",
          line_name
        )
      )$n
      if (n_line > 0L) {
        stop(
          "founder_haplotypes already contains haplotypes for line '", line_name, "'. ",
          "Drop the table or use a different line_name.",
          call. = FALSE
        )
      }
    }
  }

  n_loci <- DBI::dbGetQuery(pop$db_conn, "SELECT COUNT(*) AS n FROM genome_meta")$n
  n_loci <- as.integer(n_loci)
  if (n_loci == 0L) {
    stop("genome_meta is empty. Cannot generate founder haplotypes.", call. = FALSE)
  }

  # Read genome_meta — needed by all methods for write-back; LD methods also
  # use chr and pos_Mb for the chromosome traversal.
  genome_meta <- DBI::dbGetQuery(pop$db_conn, "SELECT * FROM genome_meta")

  message("Generating ", n_haplotypes,
          " founder haplotypes (method = \"", method, "\")...")

  # --- Dispatch ---
  if (method == "fixed") {
    if (is.null(allele_freq)) allele_freq <- 0.5
    stopifnot(is.numeric(allele_freq), length(allele_freq) == 1L,
              allele_freq >= 0, allele_freq <= 1)
    allele_freqs     <- .gen_allele_freqs_fixed(n_loci, allele_freq)
    haplotype_matrix <- .gen_haplotypes_from_freqs(n_haplotypes, allele_freqs)

  } else if (method == "uniform") {
    if (is.null(min_allele_freq)) min_allele_freq <- 0.01
    if (is.null(max_allele_freq)) max_allele_freq <- 0.99
    stopifnot(is.numeric(min_allele_freq), length(min_allele_freq) == 1L,
              min_allele_freq >= 0, min_allele_freq <= 1)
    stopifnot(is.numeric(max_allele_freq), length(max_allele_freq) == 1L,
              max_allele_freq >= 0, max_allele_freq <= 1)
    stopifnot(min_allele_freq < max_allele_freq)
    allele_freqs     <- .gen_allele_freqs_uniform(n_loci, min_allele_freq,
                                                   max_allele_freq)
    haplotype_matrix <- .gen_haplotypes_from_freqs(n_haplotypes, allele_freqs)

  } else if (method == "beta") {
    if (is.null(beta_shape1)) beta_shape1 <- 0.5
    if (is.null(beta_shape2)) beta_shape2 <- 0.5
    stopifnot(is.numeric(beta_shape1), length(beta_shape1) == 1L, beta_shape1 > 0)
    stopifnot(is.numeric(beta_shape2), length(beta_shape2) == 1L, beta_shape2 > 0)
    allele_freqs     <- .gen_allele_freqs_beta(n_loci, beta_shape1, beta_shape2)
    haplotype_matrix <- .gen_haplotypes_from_freqs(n_haplotypes, allele_freqs)

  } else if (method == "balding_nichols") {
    if (is.null(fst))       fst       <- 0.1
    if (is.null(mean_freq)) mean_freq <- 0.5
    stopifnot(is.numeric(fst),       length(fst)       == 1L, fst       > 0, fst       < 1)
    stopifnot(is.numeric(mean_freq), length(mean_freq) == 1L, mean_freq > 0, mean_freq < 1)
    allele_freqs     <- .gen_allele_freqs_balding_nichols(n_loci, fst, mean_freq)
    haplotype_matrix <- .gen_haplotypes_from_freqs(n_haplotypes, allele_freqs)

  } else if (method == "mosaic") {
    if (is.null(n_templates)) {
      n_templates <- max(2L, as.integer(ceiling(sqrt(n_haplotypes))))
    }
    if (is.null(switch_rate)) switch_rate <- 1.0
    n_templates <- as.integer(n_templates)
    stopifnot(is.numeric(n_templates), length(n_templates) == 1L, n_templates >= 2L)
    stopifnot(is.numeric(switch_rate), length(switch_rate) == 1L, switch_rate >= 0)
    if (!all(c("chr", "pos_Mb") %in% colnames(genome_meta))) {
      stop(
        "method = \"mosaic\" requires `chr` and `pos_Mb` columns in genome_meta.",
        call. = FALSE
      )
    }
    haplotype_matrix <- .gen_haplotypes_mosaic(
      n_haplotypes, n_loci, genome_meta, n_templates, switch_rate
    )
    allele_freqs <- colMeans(haplotype_matrix)

  } else if (method == "gaussian_copula") {
    if (is.null(decay_rate)) decay_rate <- 1.0
    stopifnot(is.numeric(decay_rate), length(decay_rate) == 1L, decay_rate > 0)
    if (!all(c("chr", "pos_Mb") %in% colnames(genome_meta))) {
      stop(
        "method = \"gaussian_copula\" requires `chr` and `pos_Mb` columns in genome_meta.",
        call. = FALSE
      )
    }
    result           <- .gen_haplotypes_gaussian_copula(
      n_haplotypes, n_loci, genome_meta, decay_rate
    )
    haplotype_matrix <- result$haplotype_matrix
    allele_freqs     <- colMeans(haplotype_matrix)
  }

  pop <- .write_founder_haplotypes(pop, haplotype_matrix, allele_freqs, line_name)

  line_label <- if (!is.null(line_name)) paste0(" for line '", line_name, "'") else ""
  message("  Created founder_haplotypes", line_label, " (",
          n_haplotypes, " haplotypes x ", n_loci, " loci)")

  invisible(pop)
}
