# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Autosome gamete kernel (C++), one resolved-map group
#'
#' Bit-for-bit port of [make_gametes_batch_r()]. Same arguments, same list
#' return; see the R reference for the contract. Not called directly — dispatched
#' to by the internal selector `make_gametes_batch()`.
#'
#' @param parent_allele Integer matrix (2*n_parents) x n_autosome_loci.
#' @param parent_lo_code Integer matrix, same shape: line_origin codes.
#' @param gamete_parent_idx Integer length G: 1-based packed parent row.
#' @param gamete_o Integer length G: global offspring index per gamete.
#' @param gamete_origin Integer length G: parent_origin (1/2) per gamete.
#' @param chr_start,chr_end Integer per-chromosome 1-based inclusive ranges.
#' @param chr_pos_cM Numeric per-locus positions (cM), length n_autosome_loci.
#' @param chr_len_cM Numeric per-chromosome length (cM).
#' @param base_seed Integer base seed.
#' @param store_crossovers Logical.
#' @return Named list matching make_gametes_batch_r().
#' @keywords internal
make_gametes_batch_cpp <- function(parent_allele, parent_lo_code, gamete_parent_idx, gamete_o, gamete_origin, chr_start, chr_end, chr_pos_cM, chr_len_cM, base_seed, store_crossovers) {
    .Call(`_tidybreed_make_gametes_batch_cpp`, parent_allele, parent_lo_code, gamete_parent_idx, gamete_o, gamete_origin, chr_start, chr_end, chr_pos_cM, chr_len_cM, base_seed, store_crossovers)
}

